services:
  postgres:
    image: postgres:16-alpine
    container_name: culinaryblog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: culinaryblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - culinaryblog-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d culinaryblog"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: culinary-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: culinary-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data

  seq:
    image: datalust/seq:latest
    container_name: culinary-seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seqdata:/data

  mailhog:
    image: mailhog/mailhog
    container_name: culinary-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  culinaryblog-postgres-data:
  redisdata:
  miniodata:
  seqdata:
